### ISSUE TITLE
Remove Ruby-specific snippets

### ISSUE THREAD

**Issue by itsdan** [joseramonc/rails-snippets#15]
There are snippets that are specific to Ruby: `def`, `do`, `class`. They already exist in `language-ruby` package, sometimes they're conflicting. It would be a good idea to clean those up.

**Comment by contentfree** [comment]
+1 I hate the dang `do` snippet that always uses argument. `language-ruby` already has `dop` for that.

**Comment by joseramonc** [comment]
Can someone submit a pull request removing the duplicated snippets? I agree with `dop` being clearer.
