### ISSUE TITLE
Better ERB Snippets

### ISSUE THREAD

**Issue by joryhatton** [joseramonc/rails-snippets#19]
A few more snippets should be added to the ERB cycle.  I think this is the order and availability in the original Sublime package:

* `<%= %>`
* `<%= -%>`
* `<%- -%>`
* `<%- %>`
* `<% %>`
* `<%# %>`

I especially miss having `<%- -%>` available.

**Comment by joseramonc** [comment]
@joryhatton I have updated the package to include a configuration module as there are different preferences in regard to this.

Now you can open your configuration, and paste all erb blocks that you'd like to iterate over ( and in the order you'd like to iterate ). You'll have to update your atom configuration manually to change this setting. 

In your atom configuration file. Insert the erb blocks you'd like to add and in the position you'd like to iterate over them, as an example:

```
# config.cson
"*":
  # all your configs...
  "rails-snippets":
      erbBlocks: [
        ['<%=', '%>']
        ['<%=', '-%>']
        ['<%', '%>']
        ['<%#', '%>']
      ]
```

Hope this helps you

**Comment by joryhatton** [comment]
This is perfect.  Works like a charm!  Kudos for the quick turnaround :+1:
