### ISSUE TITLE
Incompatibility with ruby-language package

### ISSUE THREAD

**Issue by Albertc** [joseramonc/rails-snippets#27]
If I install rails-snippets package, the else behaves like elseif, in a .rb file (controller or model)

when typing else:
![image](https://cloud.githubusercontent.com/assets/124529/19555730/67fb5b2c-96be-11e6-8f0d-49c2985115e7.png)

and when you press enter, or choose with mouse "else":
![image](https://cloud.githubusercontent.com/assets/124529/19555785/98699062-96be-11e6-8a54-2e058d619941.png)

It happens in a`if - else` or in a `when` 
If you want a `else`, and not `elseif true`, you have to delte back

**Comment by joseramonc** [comment]
You're right, maybe deleting or fixing [those snippets](https://github.com/joseramonc/rails-snippets/blob/master/snippets/ruby_files.cson#L96-L106) (or at least let `else` behave like `else` instead of `elsif`) would be the expected. 

Do you think it's worth to keep `elsif` snippets?

**Comment by Albertc** [comment]
I'm afraid than incompatibility can be in more snippets, not only in else-elseif, I 'm not sure, for know I will disable this package

**Comment by joseramonc** [comment]
I fixed that snippet, closing for now, but if you have more suggestions for the snippets feel free to open more issues
