### ISSUE TITLE
[Feature request] Ability to modify snippets

### ISSUE THREAD

**Issue by mityakoval** [joseramonc/rails-snippets#31]
It would be great if everyone could modify or adjust the snippets to their hearts' content. Maybe add a config that would overwrite the default snippet :)

Thanks!

**Comment by joseramonc** [comment]
Have you tried [custom snippets](http://flight-manual.atom.io/using-atom/sections/snippets/#creating-your-own-snippets)? You can copy and customize snippets there.

However, if you feel a snippet can be improved for everyone I'm open for changes or better defaults. 😄

**Comment by mityakoval** [comment]
@joseramonc Thanks, but they will conflict with the ones in this package, won't they? Or my custom snippets will have the highest priority?

For instance, `describe` + `Tab` generates `describe` with double quotes whereas I don't really do any string interpolation there so I would like to be a nerd and change that to single-quoted string. And IMHO such small subjective adjustments do not justify the changes of the snippets on the package level. 

Anyway, it doesn't really matter anymore, since I have discovered that I have 'des' + 'Tab' which does everything the way I want. 

But I just figured it might be a useful thing to have this kind of flexibility.

**Comment by joseramonc** [comment]
Yes, your local snippets should have more priority.

I'd like to support that kind of flexibility, but sadly atom doesn't support this kind of configurations (sadly) in snippets yet. Let's hope they add support for it in the near future. 

I'm closing for now, but feel free to reopen or create a new issue if you think this is still an issue.
