### ISSUE TITLE
has_many_dependent snippet produces incorrect code

### ISSUE THREAD

**Issue by DrevanTonder** [joseramonc/rails-snippets#36]
has_many_dependent produces: `has_many :categories, dependent: destroy` it should be `has_many :categories, dependent: :destroy` with the colon in front of destroy. http://guides.rubyonrails.org/association_basics.html

**Comment by joseramonc** [comment]
I missed the colon in front 😭, I'll keep it in mind the next time I update the package, or if you want to fix it I'd be happy to merge a PR.
