### ISSUE TITLE
Duplicate key errors thrown by .cson files on Atom's launch

### ISSUE THREAD

**Issue by slehmann36** [joseramonc/rails-snippets#39]
Below three errors are thrown on the launch of Atom (I guess after an Atom update):  

<img width="486" alt="screen shot 2018-05-09 at 9 43 13 am" src="https://user-images.githubusercontent.com/9215943/39791307-87b450aa-536d-11e8-8479-659ef161484c.png">

rails-snippets v2.18.0
Atom v1.26.1
MacOS v10.13.4

**Comment by joseramonc** [comment]
@slehmann36 is this related to #38 ?

**Comment by slehmann36** [comment]
@joseramonc yes, it looks like it!

**Comment by joseramonc** [comment]
I have released a new version, going to close for now, feel free to reopen if you still have the issue
