### ISSUE TITLE
Snippets should be declared on `source.ruby.rails` instead of `meta.rails.*`

### ISSUE THREAD

**Issue by kevinansfield** [joseramonc/rails-snippets#7]
See discussion here: https://discuss.atom.io/t/changing-a-files-meta-scope/16705/5

Main issue is that because the snippets are scoped to `meta.rails.*`, it's not possible to use the snippets where the `meta.rails.*` grammars/patterns aren't working.

Eg. It's not possible to use the `scope` snippet in models that use inheritance as there is no `< ActiveModel::Base` for the `meta.rails.model` grammar to be applied.

**Comment by joseramonc** [comment]
Is it resolving to another snippet? Snippets have [several scopes](https://github.com/joseramonc/rails-snippets/blob/master/snippets/models.cson#L1), what is the scope that you're using?

**Comment by kevinansfield** [comment]
Sorry Jose, seems like this was either user error on my part or something that was resolved by restarting atom. I'll close the issue as it appears that your package handles things correctly.

**Comment by joseramonc** [comment]
:+1: I'm glad it was resolved
